# Generated by Django 4.2.8 on 2023-12-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=15)),
            ],
            options={"verbose_name": "Category", "verbose_name_plural": "Categories",},
        ),
        migrations.AlterModelOptions(
            name="products",
            options={"verbose_name": "Product", "verbose_name_plural": "Products"},
        ),
    ]
