# Generated by Django 4.2.8 on 2023-12-26 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Products", "0002_category_alter_products_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Products.category",
            ),
        ),
    ]
