# Generated by Django 4.2.8 on 2023-12-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Products", "0003_products_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=15)),
            ],
            options={"verbose_name": "Level", "verbose_name_plural": "Levels",},
        ),
    ]
