# Generated by Django 4.2.8 on 2023-12-26 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Products", "0004_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="level",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Products.level",
            ),
        ),
    ]
