# Generated by Django 4.2.8 on 2023-12-26 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Products", "0006_alter_products_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="level",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Products.level",
            ),
        ),
    ]
