# Generated by Django 4.2.7 on 2024-01-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Products", "0007_alter_products_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=999),
        ),
    ]
