# Generated by Django 4.2.8 on 2024-01-10 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Products", "0009_alter_category_name_alter_level_name_reservedproduct"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservedproduct",
            options={
                "verbose_name": "Reserved Product",
                "verbose_name_plural": "Reserved Products",
            },
        ),
        migrations.RemoveField(model_name="reservedproduct", name="price",),
        migrations.RemoveField(model_name="reservedproduct", name="product_id",),
        migrations.AddField(
            model_name="reservedproduct",
            name="product",
            field=models.ForeignKey(
                default=6,
                on_delete=django.db.models.deletion.CASCADE,
                to="Products.products",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reservedproduct",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Products.category"
            ),
        ),
        migrations.AlterField(
            model_name="reservedproduct",
            name="selected_size",
            field=models.CharField(max_length=50),
        ),
    ]
