# Generated by Django 4.2.8 on 2024-01-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Products", "0010_alter_reservedproduct_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservedproduct",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
